paths:
  /missions/{missionId}/begin:
    patch:
      tags:
        - 미션 API
      summary: 미션 도전
      parameters:
      - name: missionId
        in: path
        required: true
        type: integer
        description: 미션 ID
      - name: userId
        in: query
        required: true
        schema:
          properties:
            userId:
              type: integer
              description: 유저 ID
              example: 6
      responses:
        '200':
          description: 미션 도전 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "restaurantName": "성화해장국",
                  "discription": "사진 인증하기",
                  "reward": 3,
                  "deadline": "2024-06-30 00:00:00.000000",
                  "status": "진행중"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.